name: Tag Push Workflow

on:
    push:
        tags:
            - '*'

jobs:
    config:
        runs-on: ubuntu-latest

        steps:
            - name: 'Checkout code'
              uses: actions/checkout@v2
            - name: 'Print environment variables'
              run: |
                    echo "GitHub Event Name: ${{ github.event_name }}"
                    echo "GitHub Ref: ${{ github.ref }}"
                    echo "GitHub Repository: ${{ github.repository }}"
                    echo "GitHub Actor: ${{ github.actor }}"
                    echo "GitHub Workflow: ${{ github.workflow }}"
                    echo "GitHub Action: ${{ github.action }}"
            - name: 'Clone repository'
              run: |
                    git clone --recurse-submodules https://x-access-token:${{ secrets.MY_PAT }}@github.com/IanOliv/fiap-tech-challenge.git
                    ls -la fiap-tech-challenge
                    ls -la fiap-tech-challenge/repositories
            - name: Send Message Build Failure
              uses: appleboy/discord-action@master
              with:
                color: "#00ff00"
                webhook_id: ${{ secrets.WEBHOOK_ID }}
                webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
                message: "Docker Build Failure!"

    notify:
        runs-on: ubuntu-latest
        needs: config
        steps:
            - name: Send Message Build Failure
              uses: appleboy/discord-action@master
              with:
                color: "#00ff00"
                webhook_id: ${{ secrets.WEBHOOK_ID }}
                webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
                message: "Docker Build Failure!"