name: Tag Push Workflow

on:
    push:
        tags:
            - '*'

jobs:
    config:
        runs-on: ubuntu-latest

        steps:
            - name: 'Checkout code'
              uses: actions/checkout@v2
            # - name: 'Print environment variables'
            #   run: |
            #         echo "GitHub Event Name: ${{ github.event_name }}"
            #         echo "GitHub Ref: ${{ github.ref }}"
            #         echo "GitHub Repository: ${{ github.repository }}"
            #         echo "GitHub Actor: ${{ github.actor }}"
            #         echo "GitHub Workflow: ${{ github.workflow }}"
            #         echo "GitHub Action: ${{ github.action }}"
            - name: 'Clone repository'
              run: |
                    git clone --recurse-submodules https://x-access-token:${{ secrets.MY_PAT }}@github.com/IanOliv/fiap-tech-challenge.git
            - name: Send Message Build Failure
              uses: appleboy/discord-action@master
              with:
                color: "#00ff00"
                webhook_id: ${{ secrets.WEBHOOK_ID }}
                webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
                message: "Docker Build Failure!"
    checks-typeof:
        runs-on: ubuntu-latest
        needs: config
        steps:
            - name: 'Check typeof'
              run: |
                    echo "Checking typeof..."
                    echo "GitHub Event Name: ${{ github.event_name }}"
                    echo "GitHub Ref: ${{ github.ref }}"
                    echo "GitHub Repository: ${{ github.repository }}"
                    echo "GitHub Actor: ${{ github.actor }}"
                    echo "GitHub Workflow: ${{ github.workflow }}"
                    echo "GitHub Action: ${{ github.action }}"
                    echo "GitHub Event Path: ${{ github.event_path }}"
                    echo "GitHub Event Inputs: ${{ github.event.inputs }}"
                    echo "GitHub Event Payload: ${{ github.event.payload }}"
                    echo "GitHub Event Workflow: ${{ github.event.workflow }}"
                    echo "GitHub Event Workflow Path: ${{ github.event.workflow_path }}"
                    echo "GitHub Event Workflow Run ID: ${{ github.event.workflow_run_id }}"
                    echo "GitHub Event Workflow Run Number: ${{ github.event.workflow_run_number }}"
                    echo "GitHub Event Workflow Run URL: ${{ github.event.workflow_run_url }}"
                    echo "GitHub Event Workflow Run Attempt: ${{ github.event.workflow_run_attempt }}"
                    echo "GitHub Event Workflow Run Event: ${{ github.event.workflow_run_event }}"
                    echo "GitHub Event Workflow Run Conclusions: ${{ github.event.workflow_run_conclusions }}"
                    echo "GitHub Event Workflow Run Status: ${{ github.event.workflow_run_status }}"
                    echo "GitHub Event Workflow Run Conclusion: ${{ github.event.workflow_run_conclusion }}"
                    echo "GitHub Event Workflow Run Outputs: ${{ github.event.workflow_run_outputs }}"
                    echo "GitHub Event Workflow Run Logs: ${{ github.event.workflow_run_logs }}"
                    echo "GitHub Event Workflow Run Annotations: ${{ github.event.workflow_run_annotations }}"
                    echo "GitHub Event Workflow Run Jobs: ${{ github.event.workflow_run_jobs }}"
                    echo "GitHub Event Workflow Run Steps: ${{ github.event.workflow_run_steps }}"
                    echo "GitHub Event Workflow Run Artifacts: ${{ github.event.workflow_run_artifacts }}"
                    echo "GitHub Event Workflow Run Artifacts URL: ${{ github.event.workflow_run_artifacts_url }}"
                    echo "GitHub Event Workflow Run Artifacts Archive: ${{ github.event.workflow_run_artifacts_archive }}"
                    echo "GitHub Event Workflow Run Artifacts Download: ${{ github.event.workflow_run_artifacts_download }}"
                    echo "GitHub Event Workflow Run Artifacts Upload: ${{ github.event.workflow_run_artifacts_upload }}"
                    echo
    notify:
        runs-on: ubuntu-latest
        needs: 
            - config
            - checks-typeof 
        steps:
            - name: Send Message Build Failure
              uses: appleboy/discord-action@master
              with:
                color: "#00ff00"
                webhook_id: ${{ secrets.WEBHOOK_ID }}
                webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
                message: "Docker Build Failure!"