name: Tag Push Workflow

on:
    push:
        tags:
            - '*'

jobs:
    print-env-vars:
        runs-on: ubuntu-latest

        steps:
            - name: 'Checkout code'
              uses: actions/checkout@v2
            - name: 'Print environment variables'
              run: |
                    echo "GitHub Event Name: ${{ github.event_name }}"
                    echo "GitHub Ref: ${{ github.ref }}"
                    echo "GitHub Repository: ${{ github.repository }}"
                    echo "GitHub Actor: ${{ github.actor }}"
                    echo "GitHub Workflow: ${{ github.workflow }}"
                    echo "GitHub Action: ${{ github.action }}"
            - name: 'Clone repository'
              run: |
                    git clone https://github.com/IanOliv/fiap-tech-challenge.git
                    cd fiap-tech-challenge
                    ls -la